version: '3.5'

services:
  db_chinese:
    container_name: db_chinese
    ports:
    - "5432:5432"
    environment:
        - POSTGRES_PASSWORD=root
        - POSTGRES_USER=ADMIN
    image: postgres:14.3-alpine