version: '3.5'

services:
  server:
    container_name: server_chinese
    build: .
    ports:
    - "80:80"
    volumes:
      - db_data:/var/lib/postgresql/data
  db:
    container_name: db_chinese
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=ADMIN
    image: postgres:14.3-alpine
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: {}