name: happychinese
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^2.16.1

dependencies:
  flutter:
    sdk: flutter
  adobe_xd: ^2.0.0
  svg_path_parser: ^1.0.0
  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  fluttertoast: ^8.0.9
  email_validator: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  fonts:
  - family: Segoe UI
    fonts:
      - asset: assets/fonts/Segoe-UI.ttf
  assets:
  - assets/images/